import { MessageService } from 'primeng/api';
import { Observable } from 'rxjs';
import * as i0 from "@angular/core";
export declare class MaService {
    private messageService;
    private loadingSubject;
    private downloadSubject;
    private permissions;
    private merchants;
    private userInfo;
    private partnerId;
    constructor(messageService: MessageService);
    handleError(err: any): void;
    showNotification(message: any): void;
    showLoading(): void;
    hideLoading(): void;
    getLoading(): Observable<boolean>;
    setPermissions(perms: string[]): void;
    getPermissions(): string[];
    hasPermission(p: string | string[]): boolean;
    setDownload(fileName: string): void;
    getStatusDownload(): Observable<string>;
    filterMerchantsByType(type: string): any[];
    setMerchant(perms: any[]): void;
    setUserInfo(perms: any[]): void;
    setPartnerId(perms: string): void;
    getPartnerId(): string;
    getUserInfo(): any;
    static ɵfac: i0.ɵɵFactoryDeclaration<MaService, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<MaService>;
}
export declare function convertDateToCustomFormat(dateString: string, haveHours?: boolean): string;
